### ISSUE TITLE
✨ Add the ability to hide `[ ARGS ]` from default help text. 

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [TanklesXL/glint#20]
I'm experimenting with using glint to configure [lustre's](https://github.com/lustre-labs/lustre) preview web server. The default help text prints like this:

```
% gleam run -m lustre/try -- --help
  Compiling lustre
   Compiled in 0.18s
    Running lustre/try.main
USAGE:
        lustre/try [ ARGS ] [ --host=<INT> --include-styles=<BOOL> --port=<STRING> ]

FLAGS:
        --help                  Print help information
        --host=<INT>            The port to run the server on
        --include-styles=<BOOL>         Include lustre_ui's stylesheet in your app.
        --port=<STRING>         The host to run the server on
```

This is really great except for the fact that this command will never have anything that could be a valid arg and showing `[ ARGS ]` makes it sound possible. I'd rather not write my own help text from scratch, so it'd be helpful if glint had a way for me to say "this thing doesn't take arguments, don't document them" somewhere.

**Comment by TanklesXL** [comment]
now possible with `glint.unnamed_flags(glint.EqArgs(0))`

**Comment by tankorsmash** [comment]
For anyone else, it looks like this is now through [`glint.unnamed_args(glint.EqArgs(0))`](https://hexdocs.pm/glint/glint.html#unnamed_args)

**Comment by TanklesXL** [comment]
Thanks for the clarification @tankorsmash , looks like my original comment had a typo/the wrong function name. I've updated it to not be misleading
