### ISSUE TITLE
✨ Add a `with_description` builder for the overall program.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [TanklesXL/glint#22]
For some hand-formatted cli help text, I've found it useful to include a brief description of the program at the top (see below). I think glint could benefit from similar functionality. 

```
Build and bundle Lustre applications and components for deployment and use
outside of Gleam.

Usage:
  gleam run -m lustre/build <command>

Options:
  -- --help   Show this help message.
  --minify    Minify the output.

Commands:
  app         Build a complete Lustre app for deployment.
  component   Bundle a Lustre component for use in other Web apps.
```

**Comment by TanklesXL** [comment]
Interesting idea! Would this conflict with the help text generated when a command is assigned to the root? (i.e. `glint.add([],...)`) since the root command allows you to specify a description as well
