### ISSUE TITLE
New `notes:` help output feels superfluous.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [TanklesXL/glint#27]
With the addition of named args as well as the ability to require a specific number of args, there is a new `notes:` section in the help output.

```
% gleam run -m lustre build component --help
   Compiled in 0.02s
    Running lustre.main
build component

Build a Lustre component as a portable Web Component. The generated JavaScript
module can be included in any Web page and used without Gleam or Lustre being
present.

Hint: Use the `--minify` flag to produce and smaller bundle for production.

USAGE:
    gleam run -m lustre build component <module_path> [ --minify=<BOOL> ]
notes:
* this command accepts 1 argument
* this command has named arguments: "module_path"

FLAGS:
    --help          Print help information
    --minify=<BOOL>     Minify the output
```

I think this has a few oddities:

- It should have a preceding newline to separate it from `USAGE`
- It should be in all-caps to match `USAGE` and `FLAGS`
- It repeats information the user can already see from the usage:
  - "named arguments" are a developer-facing implementation detail
  - the number of arguments accepted is already documented in the usage above

**Comment by TanklesXL** [comment]
more and more i'm inclined to agree with you on this
