### ISSUE TITLE
Example program "caps" flag capitalizes the whole message and not just the name

### ISSUE THREAD

**Issue by cmclean190** [TanklesXL/glint#33]
The `caps` flag description is "Capitalized the provided name", however the `uppercase` function is applied to `msg`, not `name`. This results in: `HELLO, JOE!` and not `Hello, JOE!`.

The correct code could be something like this:

```
let name = 
  case input.args {
    ...
  }
let name = case caps {
  True -> uppercase(name)
  False -> name
}
```

There appears to be a similar bug in the `hello` example.

**Comment by TanklesXL** [comment]
Thanks for pointing this out!

**Comment by TanklesXL** [comment]
the description of the command is now fixed in main! thanks for the heads up on this
