### ISSUE TITLE
Add the ability to provide a description for parent commands.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [TanklesXL/glint#34]
I have two commands `add esbuild` and `add tailwind`. If I run `--help` on the overall program I get:

```
% gleam run -m lustre/dev -- --help
  Compiling lustre_dev_tools
   Compiled in 0.17s
    Running lustre/dev.main
USAGE:
	gleam run -m lustre/dev [ ARGS ]

SUBCOMMANDS:
	add
```

I'd like to add a description for what the `add` family of commands do, without writing a proper command for it.

**Comment by TanklesXL** [comment]
This is a good idea, would you want this help text to apply only to the path you specify, or perhaps also for all subcommands of the provided path?

i'm thinking something like
```gleam
glint.new()
...
|> glint.path_help(["add"], "Some awesome help text")
...
```
