### ISSUE TITLE
Where does `flag` come from in the example?

### ISSUE THREAD

**Issue by czepluch** [TanklesXL/glint#38]
In the minimal example in the readme there is the line:
```
fn caps_flag() -> flag.FlagBuilder(Bool) {
```
I don't understand where `flag` is coming from. Tried replacing it with `snag`, but that also doesn't work.

**Comment by TanklesXL** [comment]
Hi there! Thanks for pointing this out, the readme is currently very much in flux as I prepare to cut v1.0.0-rc2, please use the docs for either v0.18.1 or v1.0.0-rc1 with the relevant version from hex in the meantime 😁

**Comment by TanklesXL** [comment]
I just have missed that when I updated it recently

**Comment by czepluch** [comment]
Thanks. I will give that a go :)
