### ISSUE TITLE
Cut release to silence 1.5.0-rc1 warning

### ISSUE THREAD

**Issue by richard-viney** [TanklesXL/glint#60]
Hi, would it be possible to do a small release of the current code to silence the "warning: Incompatible gleam version range" message on Gleam 1.5.0-rc1 ? Thanks!

**Comment by richard-viney** [comment]
FYI 1.5.0 is out now and this warning is still popping up on Glint v1.0.1

**Comment by TanklesXL** [comment]
Sorry I was out of town until recently, I'll be trying to get to this soon!

**Comment by richard-viney** [comment]
Thanks
